CREATE DATABASE bestTimes;
GO

USE bestTimes;
GO

CREATE TABLE BestTimes(
ID INT NOT NULL IDENTITY(1,1),
FirstName NVARCHAR(255) NOT NULL,
LastName NVARCHAR(255) NOT NULL,
Hours INT NOT NULL,
Minutes INT NOT NULL,
Seconds INT NOT NULL,
Miliseconds INT NOT NULL,
Approved BIT NOT NULL,
PRIMARY KEY (ID)
);
